name: Update README last updated

on:
  schedule:
    - cron: '0 6 * * *' # every day at 06:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update LAST_UPDATED marker
        shell: bash
        run: |
          ts=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          sed -i "s/\(<!--LAST_UPDATED:start-->\).\+\(<!--LAST_UPDATED:end-->\)/\1${ts}\2/" README.md
          echo "Updated timestamp to ${ts}"

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update last updated timestamp"
            git push
          else
            echo "No changes to commit"
          fi


